import * as React from "react"
import { CheckIcon, CodeIcon, CopyIcon, DownloadIcon, InfoIcon, TriangleAlertIcon } from "lucide-react"

import { Alert, AlertDescription, AlertTitle } from "@/registry/radix/ui/alert"
import { Button } from "@/registry/radix/ui/button"
import { CodeBlock, languageOf } from "@/editor/code-block"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/registry/radix/ui/dialog"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/registry/radix/ui/tabs"
import {
  buildAdapterFiles,
  buildGlobalsCss,
  buildOverridesCss,
  buildShadcnThemeCss,
  TAILWIND_THEME_CSS,
  type ThemeConfig,
} from "@/theme/config"

const FILE_NOTES: Record<string, string> = {
  "shadcn.theme.css":
    "The shadcn theme token mapping as CSS: every shadcn/ui variable, grouped, with the design token it aliases and what that resolves to. Generated by npm run tokens:build from the three JSON files.",
  "shadcn.overrides.css":
    "Component radius, spacing, sizes and type from Theme overrides, targeting shadcn's data-slot attributes so it works with any style. Unlayered, so it wins over Tailwind utilities (its few !important rules sit in @layer theme to beat the styles' important utilities); globals.css imports it when overrides are set.",
  "shadcn.semantic.json":
    "Light aliases + radius in the Token Bridge adapter format. This app builds it with npm run tokens:build. (The stock Token Bridge build-tokens.js currently fails on the border/radius keys, which collide with the DS border.* and radius.* groups.)",
  "dark.shadcn.semantic.json":
    "Dark aliases in the Token Bridge dark adapter format; built into the .dark block of shadcn.theme.css.",
  "shadcn.extensions.json":
    "Fonts, spacing unit and shadows aliased to DS tokens. Read by this app's build (not part of the Token Bridge contract).",
  "tailwind.theme.css":
    "Generated by npm run tokens:build. Resets Tailwind's default colors, type, radius, shadow and breakpoint scales and rebuilds them from your tokens; Tailwind names like text-sm map to the nearest token.",
  "globals.css":
    "Ready-to-paste globals.css for a shadcn project; imports tokens.css, tailwind.theme.css and shadcn.theme.css next to it.",
}

/**
 * CSS that Style Dictionary builds (npm run tokens:build) from the JSON token
 * files, and those sources. Shown here for reference only.
 */
const GENERATED_FILES: Record<string, string[]> = {
  "shadcn.theme.css": ["shadcn.semantic.json", "dark.shadcn.semantic.json", "shadcn.extensions.json"],
  "tailwind.theme.css": ["primitives.*.json", "semantic.*.json", "dark.semantic.*.json"],
}

function GeneratedFileBanner({ sources }: { sources: string[] }) {
  return (
    <Alert className="shrink-0 border-warning/60 bg-warning/10">
      <TriangleAlertIcon className="text-warning" />
      <AlertTitle>Reference only: generated by Style Dictionary</AlertTitle>
      <AlertDescription>
        <p>
          In a Style Dictionary pipeline this file is built from the .json token files (
          {sources.map((source, index) => (
            <React.Fragment key={source}>
              {index > 0 && ", "}
              <code className="font-mono">{source}</code>
            </React.Fragment>
          ))}
          ) by <code className="font-mono">npm run tokens:build</code>. Don't paste or edit it by
          hand: commit the JSON files and let the build regenerate it, or your changes will be
          overwritten.
        </p>
      </AlertDescription>
    </Alert>
  )
}

function OverridesBanner() {
  return (
    <Alert className="shrink-0 border-primary/40 bg-primary/5">
      <InfoIcon />
      <AlertTitle>Required to change default component styles</AlertTitle>
      <AlertDescription>
        <p>
          A shadcn style sets each component's own radius, spacing, sizes and type, and the theme
          variables can't reach those values. Import this file (globals.css does, after the theme
          files) whenever you change a component's defaults under Theme overrides, or the
          components keep the style's values.
        </p>
      </AlertDescription>
    </Alert>
  )
}

function download(name: string, contents: string) {
  const url = URL.createObjectURL(new Blob([contents], { type: "text/plain" }))
  const link = Object.assign(document.createElement("a"), { href: url, download: name })
  link.click()
  URL.revokeObjectURL(url)
}

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = React.useState(false)

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={async () => {
        await navigator.clipboard.writeText(value)
        setCopied(true)
        setTimeout(() => setCopied(false), 1500)
      }}
    >
      {copied ? <CheckIcon /> : <CopyIcon />}
      {copied ? "Copied" : "Copy"}
    </Button>
  )
}

export function GetCodeDialog({ config }: { config: ThemeConfig }) {
  const [open, setOpen] = React.useState(false)
  const [tab, setTab] = React.useState("shadcn.theme.css")
  const tabListRef = React.useRef<HTMLDivElement>(null)

  // Bring a partly hidden tab fully into the scrolled strip once selected.
  React.useEffect(() => {
    tabListRef.current
      ?.querySelector('[data-state="active"]')
      ?.scrollIntoView({ block: "nearest", inline: "nearest" })
  }, [tab])
  const files = React.useMemo(
    () =>
      open
        ? {
            "shadcn.theme.css": buildShadcnThemeCss(config),
            "shadcn.overrides.css": buildOverridesCss(config),
            ...buildAdapterFiles(config),
            "tailwind.theme.css": TAILWIND_THEME_CSS,
            "globals.css": buildGlobalsCss(config),
          }
        : null,
    [open, config]
  )

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <CodeIcon />
          Get Code
        </Button>
      </DialogTrigger>
      <DialogContent className="flex max-h-[85svh] flex-col sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>Theme as design-token aliases</DialogTitle>
          <DialogDescription>
            Every shadcn variable references one of your Style Dictionary tokens. Save
            these files to keep the theme in your token pipeline.
          </DialogDescription>
        </DialogHeader>
        {files && (
          <Tabs
            value={tab}
            onValueChange={setTab}
            className="min-h-0 flex-1 gap-3"
          >
            {/* Scrolls sideways when the file names don't fit; the padding
                keeps the 2px-offset focus ring from being clipped. */}
            <div className="-m-1 shrink-0 no-scrollbar scroll-fade-x overflow-x-auto p-1">
              <TabsList ref={tabListRef} className="w-max min-w-full justify-start">
                {Object.keys(files).map((name) => (
                  <TabsTrigger key={name} value={name} className="flex-none font-mono text-xs">
                    {name}
                  </TabsTrigger>
                ))}
              </TabsList>
            </div>
            {Object.entries(files).map(([name, contents]) => (
              <TabsContent key={name} value={name} className="flex min-h-0 flex-col gap-3">
                {GENERATED_FILES[name] && <GeneratedFileBanner sources={GENERATED_FILES[name]} />}
                {name === "shadcn.overrides.css" && <OverridesBanner />}
                <div className="flex items-start gap-3">
                  <p className="mr-auto text-xs text-muted-foreground">{FILE_NOTES[name]}</p>
                  <CopyButton value={contents} />
                  <Button variant="outline" size="sm" onClick={() => download(name, contents)}>
                    <DownloadIcon />
                    Download
                  </Button>
                </div>
                <CodeBlock code={contents} language={languageOf(name)} className="min-h-0 flex-1" />
              </TabsContent>
            ))}
          </Tabs>
        )}
      </DialogContent>
    </Dialog>
  )
}
