// The shadcn theme token mapping: which shadcn/ui theme variables exist, how
// they are grouped, and how the mapping is written as CSS (shadcn.theme.css).
//
// Plain JavaScript so the Node build (scripts/build-tokens.mjs) and the app
// (theme editor preview, Get Code) share one list and one formatter.

const color = (name, hint) => ({ name, kind: "color", scope: "mode", hint })
const global = (name, kind, hint) => ({ name, kind, scope: "global", hint })

/** Ordered sections; "mode" vars have light + dark aliases, "global" vars one. */
export const SHADCN_SECTIONS = [
  {
    id: "surfaces",
    title: "Surfaces",
    vars: [
      color("background", "Page background"),
      color("foreground", "Default text"),
      color("card"),
      color("card-foreground"),
      color("popover", "Menus, popovers, selects"),
      color("popover-foreground"),
    ],
  },
  {
    id: "actions",
    title: "Actions",
    vars: [
      color("primary", "Primary buttons, active states"),
      color("primary-foreground"),
      color("secondary", "Secondary buttons"),
      color("secondary-foreground"),
      color("accent", "Hover / highlighted items"),
      color("accent-foreground"),
      color("destructive", "Danger actions & errors"),
      color("destructive-foreground"),
    ],
  },
  {
    id: "status",
    title: "Status",
    vars: [
      color("warning", "Warnings (docs: Adding New Tokens)"),
      color("warning-foreground"),
    ],
  },
  {
    id: "neutrals",
    title: "Muted & Lines",
    vars: [
      color("muted", "Subdued backgrounds"),
      color("muted-foreground", "Secondary text"),
      color("border"),
      color("input", "Form control borders"),
      color("ring", "Focus ring"),
      color("ring-offset", "Gap between element and focus ring"),
    ],
  },
  {
    id: "charts",
    title: "Charts",
    vars: [1, 2, 3, 4, 5].map((n) => color(`chart-${n}`)),
  },
  {
    id: "sidebar",
    title: "Sidebar",
    vars: [
      color("sidebar"),
      color("sidebar-foreground"),
      color("sidebar-primary"),
      color("sidebar-primary-foreground"),
      color("sidebar-accent"),
      color("sidebar-accent-foreground"),
      color("sidebar-border"),
      color("sidebar-ring"),
    ],
  },
  {
    id: "selection",
    title: "Text Selection",
    vars: [color("selection"), color("selection-foreground")],
  },
  {
    id: "radius",
    title: "Radius",
    vars: [global("radius", "radius", "Base radius; sm–4xl scale from it")],
  },
  {
    id: "typography",
    title: "Typography",
    vars: [
      global("font-sans", "font", "Body font"),
      global("font-heading", "font", "Heading font"),
    ],
  },
  {
    id: "spacing",
    title: "Spacing",
    vars: [global("spacing", "spacing", "Tailwind spacing unit (p-4 = 4 × unit)")],
  },
  {
    id: "shadows",
    title: "Shadows",
    vars: ["xs", "sm", "md", "lg", "xl", "2xl"].map((size) =>
      global(`shadow-${size}`, "shadow")
    ),
  },
  {
    id: "focus",
    title: "Focus Ring",
    vars: [
      global("focus-ring-width", "border", "Outline thickness"),
      global("focus-ring-offset", "border", "Gap between element and outline"),
    ],
  },
]

export const SHADCN_VAR_NAMES = new Set(
  SHADCN_SECTIONS.flatMap((section) => section.vars.map((v) => v.name))
)

const HEADER = `/**
 * shadcn theme token mapping.
 *
 * Every shadcn/ui theme variable below is an alias of a design-system token
 * (defined in tokens.css; semantic colors switch to dark values under .dark).
 * Comments show where each alias resolves in that mode.
 *
 * Generated by scripts/build-tokens.mjs from:
 *   tokens/shadcn.semantic.json       light colors + radius
 *   tokens/dark.shadcn.semantic.json  dark colors
 *   tokens/shadcn.extensions.json     fonts, spacing, shadows, focus ring
 * Edit those files (or use the theme editor), not this file.
 */
`

const MAX_INLINE_VALUE = 32

function comment(resolved) {
  const value = resolved.value && resolved.value.length <= MAX_INLINE_VALUE ? resolved.value : ""
  return `/* ${resolved.chain.join(" → ")}${value ? ` = ${value}` : ""} */`
}

function block(selector, sections, aliasFor, resolve, mode) {
  const rows = []
  for (const section of sections) {
    const lines = section.vars
      .map((v) => [v, aliasFor(v)])
      .filter(([, path]) => path)
      .map(([v, path]) => {
        const resolved = resolve(path, mode)
        return { declaration: `--${v.name}: var(${resolved.cssVar});`, note: comment(resolved) }
      })
    if (lines.length) rows.push({ title: section.title, lines })
  }
  if (!rows.length) return ""

  // Align the comments into one column for scanning.
  const width = Math.max(...rows.flatMap((r) => r.lines.map((l) => l.declaration.length)))
  const body = rows
    .map(
      (r) =>
        `  /* ${r.title} */\n` +
        r.lines
          .map((l) => `  ${l.note ? `${l.declaration.padEnd(width)} ${l.note}` : l.declaration}`)
          .join("\n")
    )
    .join("\n\n")

  return `${selector} {\n${body}\n}\n`
}

/**
 * Formats the mapping as CSS.
 * @param {object} options
 * @param {Record<string,string>} options.light  mode var -> token path (light)
 * @param {Record<string,string>} options.dark   mode var -> token path (dark)
 * @param {Record<string,string>} options.global global var -> token path
 * @param {(path: string, mode: "light" | "dark") => {cssVar: string, chain: string[], value?: string}} options.resolve
 * @param {{root?: string, dark?: string}} [options.selectors]
 * @param {boolean} [options.header]
 */
export function formatShadcnThemeCss({
  light,
  dark,
  global: globals,
  resolve,
  selectors = {},
  header = true,
}) {
  const modeSections = SHADCN_SECTIONS.map((s) => ({
    ...s,
    vars: s.vars.filter((v) => v.scope === "mode"),
  }))

  const root = block(
    selectors.root ?? ":root",
    SHADCN_SECTIONS,
    (v) => (v.scope === "mode" ? light[v.name] : globals[v.name]),
    resolve,
    "light"
  )
  const darkBlock = block(
    selectors.dark ?? ".dark",
    modeSections,
    (v) => dark[v.name],
    resolve,
    "dark"
  )

  return [header ? HEADER : "", root, darkBlock].filter(Boolean).join("\n")
}
